import json
import pathlib
from typing import Union, Tuple
import numpy as np
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = pathlib.Path(data_fname)
        self.data = None

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to the attribute self.data."""
        with open(self.data_fname, 'r') as f:
            self.data = json.load(f)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
          Number of people in a given bin
        bins : np.ndarray
          Bin edges
        """
        # Ensure data is read
        if self.data is None:
            raise ValueError("Data has not been read. Call read_data() first.")
        
        # Extract ages from the data
        ages = [participant['age'] for participant in self.data if 'age' in participant and participant['age'] not in[None, "nan"]]

        # Define the bins
        bins = np.arange(0, 101, 10)  # Bins: [0, 10), [10, 20), ..., [90, 100]

        # Compute the Histogram
        hist, bin_edges = np.histogram(ages, bins=bins)

        # Plot the Histogram
        plt.hist(ages, bins=bins, edgecolor='black')
        plt.xlabel('Age')
        plt.ylabel('Number of Participants')
        plt.title('Age Distribution of Participants')
        plt.show()


        return hist, bin_edges
     
  
